<a href="https://colab.research.google.com/github/fatma310-bit/-/blob/main/%D8%A7%D9%83%D8%A7%D8%AF%D9%8A%D9%85%D9%8A%D8%A9_%D8%B3%D9%86%D8%AF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('اهلا يا سند')

اهلا يا سند

In [5]:
students = [
    "أحمد محمد",
    "محمد علي",
    "مريم أحمد",
    "سارة محمود"
]

print(students)

['أحمد محمد', 'محمد علي', 'مريم أحمد', 'سارة محمود']

In [8]:
import pandas as pd

students = pd.DataFrame({
    "م": [1, 2, 3, 4],
    "اسم المعلم/المعلمة": ["أستاذ أحمد", "أستاذ أحمد", "أستاذة سارة", "أستاذة سارة"],
    "اسم الطالب": ["أحمد محمد", "محمد علي", "مريم أحمد", "سارة محمود"],
    "رقم الحلقة": [1, 1, 2, 2],
    "الدوري الأول": [0, 0, 0, 0],
    "نصف العام": [0, 0, 0, 0],
    "الدوري الثاني": [0, 0, 0, 0],
    "آخر العام": [0, 0, 0, 0],
    "التفسير الأول": [0, 0, 0, 0],
    "التفسير الثاني": [0, 0, 0, 0],
    "التجويد": [0, 0, 0, 0],
    "الغياب": [0, 0, 0, 0],
    "السلوك": [0, 0, 0, 0]
})

students

,م,اسم المعلم/المعلمة,اسم الطالب,رقم الحلقة,الدوري الأول,نصف العام,الدوري الثاني,آخر العام,التفسير الأول,التفسير الثاني,التجويد,الغياب,السلوك
0,1,أستاذ أحمد,أحمد محمد,1,0,0,0,0,0,0,0,0,0
1,2,أستاذ أحمد,محمد علي,1,0,0,0,0,0,0,0,0,0
2,3,أستاذة سارة,مريم أحمد,2,0,0,0,0,0,0,0,0,0
3,4,أستاذة سارة,سارة محمود,2,0,0,0,0,0,0,0,0,0

In [9]:
students["المجموع"] = (
    students["الدوري الأول"] +
    students["نصف العام"] +
    students["الدوري الثاني"] +
    students["آخر العام"] +
    students["التفسير الأول"] +
    students["التفسير الثاني"] +
    students["التجويد"] +
    students["الغياب"] +
    students["السلوك"]
)

students[["اسم الطالب", "المجموع"]]

   اسم الطالب  المجموع
0   أحمد محمد        0
1    محمد علي        0
2   مريم أحمد        0
3  سارة محمود        0

In [10]:
def get_grade(score):
    if score >= 90:
        return "ممتاز"
    elif score >= 80:
        return "جيد جدًا"
    elif score >= 70:
        return "جيد"
    elif score >= 60:
        return "مقبول"
    else:
        return "يحتاج متابعة"

students["التقدير"] = students["المجموع"].apply(get_grade)

students[["اسم الطالب", "المجموع", "التقدير"]]

   اسم الطالب  المجموع       التقدير
0   أحمد محمد        0  يحتاج متابعة
1    محمد علي        0  يحتاج متابعة
2   مريم أحمد        0  يحتاج متابعة
3  سارة محمود        0  يحتاج متابعة

In [11]:
import ipywidgets as widgets
from IPython.display import display

name = widgets.Text(
    description="اسم الطالب:",
    placeholder="اكتبي اسم الطالب"
)

ring = widgets.IntText(
    description="رقم الحلقة:",
    value=1
)

teacher = widgets.Text(
    description="اسم المعلم:",
    placeholder="اسم المعلم أو المعلمة"
)

add_button = widgets.Button(
    description="إضافة الطالب"
)

output = widgets.Output()

def add_student(b):
    with output:
        print(
            "تمت إضافة:",
            name.value,
            "— الحلقة:",
            ring.value,
            "— المعلم:",
            teacher.value
        )

add_button.on_click(add_student)

display(name, ring, teacher, add_button, output)

Text(value='', description='اسم الطالب:', placeholder='اكتبي اسم الطالب')

IntText(value=1, description='رقم الحلقة:')

Text(value='', description='اسم المعلم:', placeholder='اسم المعلم أو المعلمة')

Button(description='إضافة الطالب', style=ButtonStyle())

Output()

تمت إضافة الطالب بنجاح ✅

,م,اسم المعلم/المعلمة,اسم الطالب,رقم الحلقة,الدوري الأول,نصف العام,الدوري الثاني,آخر العام,التفسير الأول,التفسير الثاني,التجويد,الغياب,السلوك,المجموع,التقدير
0,1,أستاذ أحمد,أحمد محمد,1,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
1,2,أستاذ أحمد,محمد علي,1,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
2,3,أستاذة سارة,مريم أحمد,2,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
3,4,أستاذة سارة,سارة محمود,2,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
4,5,منال,محمد احمد,1,0,0,0,0,0,0,0,0,0,NaN,NaN

تمت إضافة الطالب بنجاح ✅

,م,اسم المعلم/المعلمة,اسم الطالب,رقم الحلقة,الدوري الأول,نصف العام,الدوري الثاني,آخر العام,التفسير الأول,التفسير الثاني,التجويد,الغياب,السلوك,المجموع,التقدير
0,1,أستاذ أحمد,أحمد محمد,1,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
1,2,أستاذ أحمد,محمد علي,1,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
2,3,أستاذة سارة,مريم أحمد,2,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
3,4,أستاذة سارة,سارة محمود,2,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
4,5,منال,محمد احمد,1,0,0,0,0,0,0,0,0,0,NaN,NaN
5,6,منال,محمد احمد,1,0,0,0,0,0,0,0,0,0,NaN,NaN

In [13]:
def add_student_to_table(b):
    global students

    new_student = {
        "م": len(students) + 1,
        "اسم الطالب": name.value,
        "رقم الحلقة": ring.value,
        "اسم المعلم/المعلمة": teacher.value,
        "الدوري الأول": 0,
        "نصف العام": 0,
        "الدوري الثاني": 0,
        "آخر العام": 0,
        "التفسير الأول": 0,
        "التفسير الثاني": 0,
        "التجويد": 0,
        "الغياب": 0,
        "السلوك": 0
    }

    students.loc[len(students)] = new_student

    print("تمت إضافة الطالب بنجاح ✅")
    display(students)

add_button.on_click(add_student_to_table)

In [14]:
import ipywidgets as widgets
from IPython.display import display, clear_output

# خانات اختيار الطالب
student_selector = widgets.Dropdown(
    options=list(students["اسم الطالب"]),
    description="الطالب:"
)

exam_selector = widgets.Dropdown(
    options=[
        "الدوري الأول",
        "نصف العام",
        "الدوري الثاني",
        "آخر العام",
        "التفسير الأول",
        "التفسير الثاني",
        "التجويد",
        "الغياب",
        "السلوك"
    ],
    description="الدرجة:"
)

score_input = widgets.IntText(
    value=0,
    description="الدرجة:"
)

save_score = widgets.Button(
    description="حفظ الدرجة"
)

result = widgets.Output()

def save_student_score(b):
    with result:
        clear_output()

        student_name = student_selector.value
        exam_name = exam_selector.value
        score = score_input.value

        # البحث عن الطالب
        index = students.index[
            students["اسم الطالب"] == student_name
        ][0]

        # حفظ الدرجة
        students.loc[index, exam_name] = score

        # إعادة حساب المجموع
        students.loc[index, "المجموع"] = (
            students.loc[index, "الدوري الأول"] +
            students.loc[index, "نصف العام"] +
            students.loc[index, "الدوري الثاني"] +
            students.loc[index, "آخر العام"] +
            students.loc[index, "التفسير الأول"] +
            students.loc[index, "التفسير الثاني"] +
            students.loc[index, "التجويد"] +
            students.loc[index, "الغياب"] +
            students.loc[index, "السلوك"]
        )

        # إعادة حساب التقدير
        students.loc[index, "التقدير"] = get_grade(
            students.loc[index, "المجموع"]
        )

        print("تم حفظ الدرجة بنجاح ✅")
        display(
            students[
                students["اسم الطالب"] == student_name
            ][[
                "اسم الطالب",
                "الدوري الأول",
                "نصف العام",
                "الدوري الثاني",
                "آخر العام",
                "التفسير الأول",
                "التفسير الثاني",
                "التجويد",
                "الغياب",
                "السلوك",
                "المجموع",
                "التقدير"
            ]]
        )

save_score.on_click(save_student_score)

display(
    student_selector,
    exam_selector,
    score_input,
    save_score,
    result
)

Dropdown(description='الطالب:', options=('أحمد محمد', 'محمد علي', 'مريم أحمد', 'سارة محمود', 'محمد احمد ', 'مح…

Dropdown(description='الدرجة:', options=('الدوري الأول', 'نصف العام', 'الدوري الثاني', 'آخر العام', 'التفسير ا…

IntText(value=0, description='الدرجة:')

Button(description='حفظ الدرجة', style=ButtonStyle())

Output()

In [15]:
from IPython.display import display

display(
    students.style
    .set_caption("إدارة حلقات القرآن")
    .format({
        "الدوري الأول": "{:.0f}",
        "نصف العام": "{:.0f}",
        "الدوري الثاني": "{:.0f}",
        "آخر العام": "{:.0f}",
        "التفسير الأول": "{:.0f}",
        "التفسير الثاني": "{:.0f}",
        "التجويد": "{:.0f}",
        "الغياب": "{:.0f}",
        "السلوك": "{:.0f}",
        "المجموع": "{:.0f}"
    })
)

In [16]:
# حفظ بيانات الطلاب في ملف Excel

file_name = "بيانات_حلقات_القرآن.xlsx"

students.to_excel(file_name, index=False)

print("تم حفظ البيانات بنجاح ✅")
print("اسم الملف:", file_name)

تم حفظ البيانات بنجاح ✅
اسم الملف: بيانات_حلقات_القرآن.xlsx

In [17]:
from google.colab import files

files.download("بيانات_حلقات_القرآن.xlsx")

In [18]:
import ipywidgets as widgets
from IPython.display import display

title = widgets.HTML(
    value="""
    <h1 style="text-align:center;">
        إدارة حلقات القرآن
    </h1>
    <p style="text-align:center;">
        نظام إدارة الطلاب والدرجات
    </p>
    """
)

students_btn = widgets.Button(
    description="👨‍🎓 الطلاب",
    layout=widgets.Layout(width="150px", height="50px")
)

rings_btn = widgets.Button(
    description="📚 الحلقات",
    layout=widgets.Layout(width="150px", height="50px")
)

grades_btn = widgets.Button(
    description="📝 الدرجات",
    layout=widgets.Layout(width="150px", height="50px")
)

results_btn = widgets.Button(
    description="📊 النتائج",
    layout=widgets.Layout(width="150px", height="50px")
)

save_btn = widgets.Button(
    description="💾 حفظ",
    layout=widgets.Layout(width="150px", height="50px")
)

menu = widgets.HBox([
    students_btn,
    rings_btn,
    grades_btn,
    results_btn,
    save_btn
])

display(title)
display(menu)

HTML(value='\n    <h1 style="text-align:center;">\n        إدارة حلقات القرآن\n    </h1>\n    <p style="text-a…

HBox(children=(Button(description='👨\u200d🎓 الطلاب', layout=Layout(height='50px', width='150px'), style=Button…

In [38]:
from IPython.display import clear_output, display

def show_students(b=None):
    clear_output(wait=True)

    back_btn = widgets.Button(
        description="⬅️ الرئيسية",
        layout=widgets.Layout(width="150px", height="45px")
    )

    title = widgets.HTML(
        value="""
        <h2 style="text-align:center;">
            👨‍🎓 سجل الطلاب
        </h2>
        """
    )

    display(title)
    display(back_btn)
    display(students)

    back_btn.on_click(show_home)


def show_home(b=None):
    clear_output(wait=True)

    display(title)
    display(menu)


students_btn.on_click(show_students)

display(title)
display(menu)

HTML(value='\n    <h1 style="text-align:center;">\n        إدارة حلقات القرآن\n    </h1>\n    <p style="text-a…

HBox(children=(Button(description='👨\u200d🎓 الطلاب', layout=Layout(height='50px', width='150px'), style=Button…

In [37]:
# شاشة إضافة طالب جديدة

def show_add_student(b=None):
    clear_output(wait=True)

    title_add = widgets.HTML(
        value="""
        <h2 style="text-align:center;">
            ➕ إضافة طالب جديد
        </h2>
        """
    )

    student_name = widgets.Text(
        description="اسم الطالب:",
        placeholder="اكتبي اسم الطالب"
    )

    ring_number = widgets.IntText(
        description="رقم الحلقة:",
        value=1
    )

    teacher_name = widgets.Text(
        description="المعلم/المعلمة:",
        placeholder="اكتبي اسم المعلم أو المعلمة"
    )

    add_button = widgets.Button(
        description="💾 حفظ الطالب",
        button_style="success"
    )

    back_button = widgets.Button(
        description="⬅️ الرئيسية"
    )

    message = widgets.Output()

    def add_new_student(b):
        global students

        with message:
            clear_output()

            if student_name.value.strip() == "":
                print("⚠️ من فضلك اكتبي اسم الطالب.")
                return

            new_student = {
                "م": len(students) + 1,
                "اسم الطالب": student_name.value.strip(),
                "رقم الحلقة": ring_number.value,
                "اسم المعلم/المعلمة": teacher_name.value.strip(),
                "الدوري الأول": 0,
                "نصف العام": 0,
                "الدوري الثاني": 0,
                "آخر العام": 0,
                "التفسير الأول": 0,
                "التفسير الثاني": 0,
                "التجويد": 0,
                "الغياب": 0,
                "السلوك": 0,
                "المجموع": 0,
                "التقدير": "يحتاج متابعة"
            }

            students.loc[len(students)] = new_student

            print("✅ تم إضافة الطالب بنجاح!")

            student_name.value = ""
            teacher_name.value = ""

    add_button.on_click(add_new_student)
    back_button.on_click(show_home)

    display(title_add)
    display(student_name)
    display(ring_number)
    display(teacher_name)
    display(add_button)
    display(back_button)
    display(message)

In [35]:
def show_students(b=None):
    clear_output(wait=True)

    title_students = widgets.HTML(
        value="""
        <h2 style="text-align:center;">
            👨‍🎓 سجل الطلاب
        </h2>
        """
    )

    add_btn = widgets.Button(
        description="➕ إضافة طالب",
        button_style="success",
        layout=widgets.Layout(width="180px", height="45px")
    )

    back_btn = widgets.Button(
        description="⬅️ الرئيسية",
        layout=widgets.Layout(width="150px", height="45px")
    )

    add_btn.on_click(show_add_student)
    back_btn.on_click(show_home)

    display(title_students)
    display(add_btn)
    display(back_btn)
    display(students)

In [39]:
# إعادة ربط زر الطلاب بشاشة الطلاب
students_btn.on_click(show_students)

# إعادة عرض الصفحة الرئيسية
clear_output(wait=True)
display(title)
display(menu)

HTML(value='\n        <h2 style="text-align:center;">\n            👨\u200d🎓 سجل الطلاب\n        </h2>\n       …

Button(description='⬅️ الرئيسية', layout=Layout(height='45px', width='150px'), style=ButtonStyle())

,م,اسم المعلم/المعلمة,اسم الطالب,رقم الحلقة,الدوري الأول,نصف العام,الدوري الثاني,آخر العام,التفسير الأول,التفسير الثاني,التجويد,الغياب,السلوك,المجموع,التقدير
0,1,أستاذ أحمد,أحمد محمد,1,30,0,0,0,0,0,0,0,0,30.0,يحتاج متابعة
1,2,أستاذ أحمد,محمد علي,1,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
2,3,أستاذة سارة,مريم أحمد,2,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
3,4,أستاذة سارة,سارة محمود,2,0,0,0,0,0,0,0,0,0,0.0,يحتاج متابعة
4,5,منال,محمد احمد,1,0,0,0,0,0,0,0,0,0,NaN,NaN
5,6,منال,محمد احمد,1,0,0,0,0,0,0,0,0,0,NaN,NaN

In [42]:
def show_students_new(b=None):
    clear_output(wait=True)

    title_students = widgets.HTML(
        value="""
        <h2 style="text-align:center;">
            👨‍🎓 سجل الطلاب
        </h2>
        """
    )

    add_btn = widgets.Button(
        description="➕ إضافة طالب",
        button_style="success",
        layout=widgets.Layout(
            width="180px",
            height="45px"
        )
    )

    back_btn = widgets.Button(
        description="⬅️ الرئيسية",
        layout=widgets.Layout(
            width="150px",
            height="45px"
        )
    )

    add_btn.on_click(show_add_student)
    back_btn.on_click(show_home)

    display(title_students)
    display(add_btn)
    display(back_btn)
    display(students)


# نربط زر الطلاب بالنسخة الجديدة
students_btn._click_handlers.callbacks = []
students_btn.on_click(show_students_new)

# نعرض الصفحة الرئيسية
clear_output(wait=True)
display(title)
display(menu)

HTML(value='\n    <h1 style="text-align:center;">\n        إدارة حلقات القرآن\n    </h1>\n    <p style="text-a…

HBox(children=(Button(description='👨\u200d🎓 الطلاب', layout=Layout(height='50px', width='150px'), style=Button…

In [41]:
def search_students(b=None):
    search_text = search_box.value.strip()

    with search_result:
        clear_output()

        if search_text == "":
            display(students)
            return

        result = students[
            students["اسم الطالب"].astype(str).str.contains(
                search_text,
                case=False,
                na=False
            )
        ]

        if result.empty:
            print("❌ لم يتم العثور على الطالب.")
        else:
            display(result)


search_box = widgets.Text(
    description="🔎 بحث:",
    placeholder="اكتبي اسم الطالب"
)

search_result = widgets.Output()

search_button = widgets.Button(
    description="بحث",
    layout=widgets.Layout(width="100px")
)

search_button.on_click(search_students)

In [43]:
display(search_box, search_button, search_result)

Text(value='', description='🔎 بحث:', placeholder='اكتبي اسم الطالب')

Button(description='بحث', layout=Layout(width='100px'), style=ButtonStyle())

Output()

In [44]:
def show_students_final(b=None):
    clear_output(wait=True)

    title_students = widgets.HTML(
        value="""
        <h2 style="text-align:center;">
            👨‍🎓 إدارة الطلاب
        </h2>
        """
    )

    search_box = widgets.Text(
        description="🔎 بحث:",
        placeholder="اكتبي اسم الطالب"
    )

    search_btn = widgets.Button(
        description="بحث",
        layout=widgets.Layout(width="100px")
    )

    add_btn = widgets.Button(
        description="➕ إضافة طالب",
        button_style="success",
        layout=widgets.Layout(width="160px")
    )

    all_btn = widgets.Button(
        description="📋 كل الطلاب",
        layout=widgets.Layout(width="140px")
    )

    back_btn = widgets.Button(
        description="⬅️ الرئيسية",
        layout=widgets.Layout(width="140px")
    )

    result = widgets.Output()

    def search(b):
        with result:
            clear_output()

            text = search_box.value.strip()

            if text == "":
                display(students)
                return

            found = students[
                students["اسم الطالب"].astype(str).str.contains(
                    text,
                    case=False,
                    na=False
                )
            ]

            if found.empty:
                print("❌ لم يتم العثور على الطالب.")
            else:
                display(found)

    def show_all(b):
        with result:
            clear_output()
            display(students)

    search_btn.on_click(search)
    all_btn.on_click(show_all)
    add_btn.on_click(show_add_student)
    back_btn.on_click(show_home)

    display(title_students)

    display(
        widgets.HBox([
            search_box,
            search_btn
        ])
    )

    display(
        widgets.HBox([
            add_btn,
            all_btn,
            back_btn
        ])
    )

    display(result)

    # عرض كل الطلاب عند فتح الشاشة
    with result:
        display(students)


# ربط زر الطلاب بالواجهة الجديدة
students_btn._click_handlers.callbacks = []
students_btn.on_click(show_students_final)

# عرض الرئيسية
clear_output(wait=True)
display(title)
display(menu)

HTML(value='\n        <h2 style="text-align:center;">\n            👨\u200d🎓 إدارة الطلاب\n        </h2>\n     …

HBox(children=(Text(value='', description='🔎 بحث:', placeholder='اكتبي اسم الطالب'), Button(description='بحث',…

HBox(children=(Button(button_style='success', description='➕ إضافة طالب', layout=Layout(width='160px'), style=…

Output()

In [47]:
def show_grades(b=None):
    clear_output(wait=True)

    title_grades = widgets.HTML(
        value="""
        <h2 style="text-align:center;">
            📝 درجات الطلاب
        </h2>
        """
    )

    student_box = widgets.Dropdown(
        options=list(students["اسم الطالب"]),
        description="الطالب:"
    )

    exam_box = widgets.Dropdown(
        options=[
            "الدوري الأول",
            "نصف العام",
            "الدوري الثاني",
            "آخر العام",
            "التفسير الأول",
            "التفسير الثاني",
            "التجويد",
            "الغياب",
            "السلوك"
        ],
        description="المادة:"
    )

    score_box = widgets.IntText(
        value=0,
        description="الدرجة:"
    )

    save_btn = widgets.Button(
        description="💾 حفظ الدرجة",
        button_style="success"
    )

    back_btn = widgets.Button(
        description="⬅️ الرئيسية"
    )

    result = widgets.Output()

    def save_grade(b):
        with result:
            clear_output()

            if len(students) == 0:
                print("❌ لا يوجد طلاب.")
                return

            student_name = student_box.value
            exam_name = exam_box.value
            score = score_box.value

            # الحدود القصوى للدرجات
            max_scores = {
                "الدوري الأول": 40,
                "نصف العام": 100,
                "الدوري الثاني": 40,
                "آخر العام": 100,
                "التفسير الأول": 10,
                "التفسير الثاني": 10,
                "التجويد": 10,
                "الغياب": 10,
                "السلوك": 10
            }

            maximum = max_scores[exam_name]

            if score < 0 or score > maximum:
                print(f"⚠️ الدرجة يجب أن تكون من 0 إلى {maximum}.")
                return

            index = students.index[
                students["اسم الطالب"] == student_name
            ][0]

            students.loc[index, exam_name] = score

            # حساب المجموع
            total = sum(
                students.loc[index, subject]
                for subject in max_scores
            )

            students.loc[index, "المجموع"] = total
            students.loc[index, "التقدير"] = get_grade(total)

            print("✅ تم حفظ الدرجة بنجاح!")
            print(f"الطالب: {student_name}")
            print(f"{exam_name}: {score} من {maximum}")
            print(f"المجموع: {total}")
            print(f"التقدير: {get_grade(total)}")

    save_btn.on_click(save_grade)
    back_btn.on_click(show_home)

    display(title_grades)
    display(student_box)
    display(exam_box)
    display(score_box)
    display(save_btn)
    display(back_btn)
    display(result)


# ربط زر الدرجات بالواجهة الجديدة
grades_btn._click_handlers.callbacks = []
grades_btn.on_click(show_grades)

# العودة للرئيسية
clear_output(wait=True)
display(title)
display(menu)

HTML(value='\n        <h2 style="text-align:center;">\n            📝 درجات الطلاب\n        </h2>\n        ')

Dropdown(description='الطالب:', options=('أحمد محمد', 'محمد علي', 'مريم أحمد', 'سارة محمود', 'محمد احمد ', 'مح…

Dropdown(description='المادة:', options=('الدوري الأول', 'نصف العام', 'الدوري الثاني', 'آخر العام', 'التفسير ا…

IntText(value=0, description='الدرجة:')

Button(button_style='success', description='💾 حفظ الدرجة', style=ButtonStyle())

Button(description='⬅️ الرئيسية', style=ButtonStyle())

Output()

In [48]:
def save_data():
    file_name = "بيانات_حلقات_القرآن.xlsx"
    students.to_excel(file_name, index=False)
    return file_name

print("💾 نظام حفظ البيانات جاهز")

💾 نظام حفظ البيانات جاهز

In [49]:
def save_button_action(b):
    file_name = save_data()

    with save_message:
        clear_output()
        print("✅ تم حفظ جميع البيانات بنجاح")
        print("📄 الملف:", file_name)


save_message = widgets.Output()

save_btn_main = widgets.Button(
    description="💾 حفظ البيانات",
    button_style="success",
    layout=widgets.Layout(
        width="180px",
        height="50px"
    )
)

save_btn_main.on_click(save_button_action)

display(save_btn_main)
display(save_message)

Button(button_style='success', description='💾 حفظ البيانات', layout=Layout(height='50px', width='180px'), styl…

Output()

In [50]:
from google.colab import files
import os

download_btn = widgets.Button(
    description="📥 تحميل ملف Excel",
    button_style="info",
    layout=widgets.Layout(
        width="200px",
        height="50px"
    )
)

download_message = widgets.Output()

def download_excel(b):
    file_name = save_data()

    with download_message:
        clear_output()
        print("📥 جاري تجهيز ملف Excel...")
        files.download(file_name)
        print("✅ تم تجهيز الملف للتحميل")

download_btn.on_click(download_excel)

display(download_btn)
display(download_message)

Button(button_style='info', description='📥 تحميل ملف Excel', layout=Layout(height='50px', width='200px'), styl…

Output()